%bcond_without tests
%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/kilted/.*$
%global __requires_exclude_from ^/opt/ros/kilted/.*$

%global __cmake_in_source_build 1

Name:           ros-kilted-rcl
Version:        10.1.2
Release:        1%{?dist}%{?release_suffix}
Summary:        ROS rcl package

License:        Apache License 2.0
Source0:        %{name}-%{version}.tar.gz

Requires:       libyaml-devel
Requires:       ros-kilted-libyaml-vendor
Requires:       ros-kilted-rcl-interfaces
Requires:       ros-kilted-rcl-logging-interface
Requires:       ros-kilted-rcl-logging-spdlog
Requires:       ros-kilted-rcl-yaml-param-parser
Requires:       ros-kilted-rcutils
Requires:       ros-kilted-rmw
Requires:       ros-kilted-rmw-implementation
Requires:       ros-kilted-rosidl-runtime-c
Requires:       ros-kilted-service-msgs
Requires:       ros-kilted-tracetools
Requires:       ros-kilted-type-description-interfaces
Requires:       ros-kilted-ros-workspace
BuildRequires:  libyaml-devel
BuildRequires:  ros-kilted-ament-cmake-gen-version-h
BuildRequires:  ros-kilted-ament-cmake-ros
BuildRequires:  ros-kilted-libyaml-vendor
BuildRequires:  ros-kilted-rcl-interfaces
BuildRequires:  ros-kilted-rcl-logging-interface
BuildRequires:  ros-kilted-rcl-logging-spdlog
BuildRequires:  ros-kilted-rcl-yaml-param-parser
BuildRequires:  ros-kilted-rcutils
BuildRequires:  ros-kilted-rmw-implementation
BuildRequires:  ros-kilted-rosidl-runtime-c
BuildRequires:  ros-kilted-service-msgs
BuildRequires:  ros-kilted-tracetools
BuildRequires:  ros-kilted-type-description-interfaces
BuildRequires:  ros-kilted-ros-workspace
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%if 0%{?with_tests}
BuildRequires:  ros-kilted-ament-cmake-gtest
BuildRequires:  ros-kilted-ament-lint-auto
BuildRequires:  ros-kilted-ament-lint-common
BuildRequires:  ros-kilted-launch
BuildRequires:  ros-kilted-launch-testing
BuildRequires:  ros-kilted-launch-testing-ament-cmake
BuildRequires:  ros-kilted-mimick-vendor
BuildRequires:  ros-kilted-osrf-testing-tools-cpp
BuildRequires:  ros-kilted-rmw
BuildRequires:  ros-kilted-rmw-implementation-cmake
BuildRequires:  ros-kilted-rosidl-runtime-cpp
BuildRequires:  ros-kilted-test-msgs
%endif

%description
The ROS client library common implementation. This package contains an API which
builds on the ROS middleware API and is optionally built upon by the other ROS
client libraries.

%prep
%autosetup -p1

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
mkdir -p .obj-%{_target_platform} && cd .obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/kilted" \
    -DAMENT_PREFIX_PATH="/opt/ros/kilted" \
    -DCMAKE_PREFIX_PATH="/opt/ros/kilted" \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
%if !0%{?with_tests}
    -DBUILD_TESTING=OFF \
%endif
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
%make_install -C .obj-%{_target_platform}

%if 0%{?with_tests}
%check
# Look for a Makefile target with a name indicating that it runs tests
TEST_TARGET=$(%__make -qp -C .obj-%{_target_platform} | sed "s/^\(test\|check\):.*/\\1/;t f;d;:f;q0")
if [ -n "$TEST_TARGET" ]; then
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree and source it.  It will set things like
# CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/kilted/setup.sh" ]; then . "/opt/ros/kilted/setup.sh"; fi
CTEST_OUTPUT_ON_FAILURE=1 \
    %make_build -C .obj-%{_target_platform} $TEST_TARGET || echo "RPM TESTS FAILED"
else echo "RPM TESTS SKIPPED"; fi
%endif

%files
/opt/ros/kilted

%changelog
* Tue Sep 30 2025 Audrow Nash <audrow@openrobotics.org> - 10.1.2-1
- Autogenerated by Bloom

* Mon Jun 23 2025 Audrow Nash <audrow@openrobotics.org> - 10.1.1-1
- Autogenerated by Bloom

* Tue Apr 22 2025 Audrow Nash <audrow@openrobotics.org> - 10.1.0-2
- Autogenerated by Bloom

* Fri Apr 04 2025 Audrow Nash <audrow@openrobotics.org> - 10.1.0-1
- Autogenerated by Bloom

* Fri Jan 31 2025 Audrow Nash <audrow@openrobotics.org> - 10.0.2-1
- Autogenerated by Bloom

* Wed Nov 20 2024 Audrow Nash <audrow@openrobotics.org> - 10.0.1-1
- Autogenerated by Bloom

* Thu Oct 03 2024 Audrow Nash <audrow@openrobotics.org> - 10.0.0-1
- Autogenerated by Bloom

* Mon Jul 29 2024 Audrow Nash <audrow@openrobotics.org> - 9.4.1-1
- Autogenerated by Bloom

* Mon Jun 17 2024 Audrow Nash <audrow@openrobotics.org> - 9.4.0-1
- Autogenerated by Bloom

* Fri Apr 26 2024 Audrow Nash <audrow@openrobotics.org> - 9.3.0-1
- Autogenerated by Bloom

* Tue Apr 16 2024 Audrow Nash <audrow@openrobotics.org> - 9.2.1-1
- Autogenerated by Bloom

* Thu Mar 28 2024 Audrow Nash <audrow@openrobotics.org> - 9.2.0-1
- Autogenerated by Bloom

* Wed Mar 06 2024 Audrow Nash <audrow@openrobotics.org> - 9.1.0-2
- Autogenerated by Bloom

